#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color

#Clear launch before open
clear

echo -e "${GREEN}+${LIGHTBLUE}------------------------------------------------${GREEN}+"
echo -e "+${LIGHTGRAY}         SOBRE PROYECTO HTRX${GREEN}          +"
echo -e "+------------------------------------------------+"
echo -e "${GREEN}+${LIGHTBLUE} [Version]${LIGHTGRAY}1.0${GREEN}                                   +"
echo -e "${GREEN}+${LIGHTBLUE} [Release Date]${LIGHTGRAY}2018${GREEN}                       +"
echo -e "${GREEN}+${LIGHTBLUE} [Developed By]${LIGHTGRAY}HTRX#Ինչու ոչ${GREEN}                +"
echo -e "${GREEN}+${LIGHTBLUE} [Coder]${LIGHTGRAY}HTRX#Ինչու ոչ${GREEN}                       +"
echo -e "${GREEN}+${LIGHTBLUE} [Beta Tester]${LIGHTGRAY}HTRX#Ինչու ոչ & VGB${GREEN}           +"
echo -e "${GREEN}+${LIGHTBLUE}------------------------------------------------${GREEN}+"
echo -e "${LIGHTBLUE}                   [DISCLAMER]"                     

echo -e "${RED}"
echo -e "No nos hacemos responsables de lo que utiliza esta herramienta para lograr."
echo -e "Esta herramienta esta diseñada para uso privado / personal para realizar pruebas de estrés en " 
echo -e "Equipo de red. Puede ser ilegal usar este software para otros fines"
echo -e "que su uso previsto"
echo -e ""
echo -e "Esta herramienta ha conseguido HTRX # ¿Por que no dar creditos?"
#do chmod for change permissions of all files (you can have problem if you are not root.If you have problem delete chmod 777 *)
chmod 777 *
read
clear





